development:
  adapter: mysql
  database: blog_development
  username: root
  password:
  host: localhost
test: &TEST
  adapter: mysql
  database: blog_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: blog_production
  username: root
  password: 
  host: localhost

cucumber:
  <<: *TEST